<?php

namespace App\Services\BrandDna;

/**
 * Koneva Brand DNA Taxonomy
 *
 * Defines the 10 proprietary DNA archetypes and their keyword signal maps.
 * This framework is owned by Koneva — AI does not determine DNA, it only narrates it.
 */
class DnaTaxonomy
{
    const DNA_TYPES = [
        'craftsmanship' => [
            'name'        => 'Craftsmanship',
            'name_id'     => 'Keunggulan Kualitas',
            'character'   => 'Kualitas, detail, presisi, premium',
            'description' => 'Brand yang menempatkan kualitas di atas segalanya. Setiap detail diperhatikan, setiap produk adalah karya.',
            'icon'        => 'fa-gem',
            'color'       => '#92400e',
            'bg_color'    => 'rgba(146,64,14,0.08)',
            'border'      => 'rgba(146,64,14,0.25)',
            'badge_bg'    => '#fef3c7',
            'badge_text'  => '#92400e',
        ],
        'community' => [
            'name'        => 'Community',
            'name_id'     => 'Komunitas & Kedekatan',
            'character'   => 'Kebersamaan, kedekatan, kepercayaan',
            'description' => 'Brand yang tumbuh dari dan untuk komunitas. Pelanggan adalah bagian dari cerita.',
            'icon'        => 'fa-people-group',
            'color'       => '#065f46',
            'bg_color'    => 'rgba(6,95,70,0.07)',
            'border'      => 'rgba(6,95,70,0.25)',
            'badge_bg'    => '#d1fae5',
            'badge_text'  => '#065f46',
        ],
        'innovation' => [
            'name'        => 'Innovation',
            'name_id'     => 'Inovasi & Kreativitas',
            'character'   => 'Kreatif, modern, visioner',
            'description' => 'Brand yang selalu berada di depan. Selalu ada sesuatu yang baru dan berbeda.',
            'icon'        => 'fa-rocket',
            'color'       => '#1d4ed8',
            'bg_color'    => 'rgba(29,78,216,0.07)',
            'border'      => 'rgba(29,78,216,0.25)',
            'badge_bg'    => '#dbeafe',
            'badge_text'  => '#1d4ed8',
        ],
        'authority' => [
            'name'        => 'Authority',
            'name_id'     => 'Otoritas & Kepakaran',
            'character'   => 'Ahli, profesional, terpercaya',
            'description' => 'Brand yang menjadi rujukan. Audiensnya datang bukan hanya untuk beli, tapi untuk belajar.',
            'icon'        => 'fa-graduation-cap',
            'color'       => '#1e3a5f',
            'bg_color'    => 'rgba(30,58,95,0.07)',
            'border'      => 'rgba(30,58,95,0.25)',
            'badge_bg'    => '#e0f2fe',
            'badge_text'  => '#1e3a5f',
        ],
        'lifestyle' => [
            'name'        => 'Lifestyle',
            'name_id'     => 'Gaya Hidup',
            'character'   => 'Aspirasional, estetik, tren',
            'description' => 'Brand yang menjual identitas. Produknya adalah simbol gaya hidup yang diidamkan.',
            'icon'        => 'fa-star',
            'color'       => '#7c3aed',
            'bg_color'    => 'rgba(124,58,237,0.07)',
            'border'      => 'rgba(124,58,237,0.25)',
            'badge_bg'    => '#ede9fe',
            'badge_text'  => '#7c3aed',
        ],
        'value_driven' => [
            'name'        => 'Value Driven',
            'name_id'     => 'Berbasis Nilai',
            'character'   => 'Idealisme, prinsip, transparansi',
            'description' => 'Brand yang dipandu oleh nilai dan prinsip. Audiensnya setia bukan karena produk, tapi karena percaya pada misi.',
            'icon'        => 'fa-heart',
            'color'       => '#047857',
            'bg_color'    => 'rgba(4,120,87,0.07)',
            'border'      => 'rgba(4,120,87,0.25)',
            'badge_bg'    => '#d1fae5',
            'badge_text'  => '#047857',
        ],
        'efficiency' => [
            'name'        => 'Efficiency',
            'name_id'     => 'Efisiensi & Kepraktisan',
            'character'   => 'Cepat, praktis, solusi instan',
            'description' => 'Brand yang menghargai waktu pelanggan. Solusi cepat, proses mudah, hasil langsung terasa.',
            'icon'        => 'fa-bolt',
            'color'       => '#b45309',
            'bg_color'    => 'rgba(180,83,9,0.07)',
            'border'      => 'rgba(180,83,9,0.25)',
            'badge_bg'    => '#fef3c7',
            'badge_text'  => '#b45309',
        ],
        'personal_connection' => [
            'name'        => 'Personal Connection',
            'name_id'     => 'Koneksi Personal',
            'character'   => 'Owner-centric, personal, autentik',
            'description' => 'Brand yang dijual bersama ownernya. Kepercayaan terbangun karena pelanggan mengenal orangnya.',
            'icon'        => 'fa-user-circle',
            'color'       => '#be185d',
            'bg_color'    => 'rgba(190,24,93,0.07)',
            'border'      => 'rgba(190,24,93,0.25)',
            'badge_bg'    => '#fce7f3',
            'badge_text'  => '#be185d',
        ],
        'local_pride' => [
            'name'        => 'Local Pride',
            'name_id'     => 'Kebanggaan Lokal',
            'character'   => 'Lokal, budaya, Indonesia',
            'description' => 'Brand yang menjadikan identitas lokal sebagai kekuatan. Bangga Indonesia, tumbuh dari akar.',
            'icon'        => 'fa-map-marker-alt',
            'color'       => '#dc2626',
            'bg_color'    => 'rgba(220,38,38,0.07)',
            'border'      => 'rgba(220,38,38,0.25)',
            'badge_bg'    => '#fee2e2',
            'badge_text'  => '#dc2626',
        ],
        'transformation' => [
            'name'        => 'Transformation',
            'name_id'     => 'Transformasi & Hasil',
            'character'   => 'Perubahan nyata, before-after, hasil',
            'description' => 'Brand yang menjual perubahan. Pelanggan datang karena ingin menjadi versi yang lebih baik.',
            'icon'        => 'fa-arrows-rotate',
            'color'       => '#6b21a8',
            'bg_color'    => 'rgba(107,33,168,0.07)',
            'border'      => 'rgba(107,33,168,0.25)',
            'badge_bg'    => '#f3e8ff',
            'badge_text'  => '#6b21a8',
        ],
    ];

    /**
     * Keyword signal map for Indonesian text.
     * Format: 'keyword' => ['dna_type' => weight (1-25)]
     */
    const KEYWORD_MAP = [
        // ── Craftsmanship ───────────────────────────────────────────
        'perfeksionis'    => ['craftsmanship' => 20, 'authority' => 5],
        'detail oriented' => ['craftsmanship' => 22],
        'detail'          => ['craftsmanship' => 15],
        'teliti'          => ['craftsmanship' => 18, 'authority' => 5],
        'cermat'          => ['craftsmanship' => 15],
        'presisi'         => ['craftsmanship' => 20],
        'premium'         => ['craftsmanship' => 25, 'lifestyle' => 10],
        'kualitas tinggi' => ['craftsmanship' => 25],
        'berkualitas'     => ['craftsmanship' => 20],
        'high quality'    => ['craftsmanship' => 22],
        'eksklusif'       => ['craftsmanship' => 15, 'lifestyle' => 15],
        'mewah'           => ['craftsmanship' => 18, 'lifestyle' => 18],
        'luxury'          => ['craftsmanship' => 18, 'lifestyle' => 18],
        'standar tinggi'  => ['craftsmanship' => 20],
        'handmade'        => ['craftsmanship' => 22, 'local_pride' => 8],
        'hand made'       => ['craftsmanship' => 22, 'local_pride' => 8],
        'buatan tangan'   => ['craftsmanship' => 22, 'local_pride' => 10],
        'artisan'         => ['craftsmanship' => 20, 'local_pride' => 8],
        'awet'            => ['craftsmanship' => 15],
        'tahan lama'      => ['craftsmanship' => 18],
        'durable'         => ['craftsmanship' => 18],
        'material terbaik' => ['craftsmanship' => 20],
        'bahan terbaik'   => ['craftsmanship' => 20],
        'bahan premium'   => ['craftsmanship' => 22, 'lifestyle' => 5],
        'bahan berkualitas' => ['craftsmanship' => 20],
        'tidak asal'      => ['craftsmanship' => 18],
        'tidak sembarangan' => ['craftsmanship' => 18],
        'kontrol kualitas' => ['craftsmanship' => 20],
        'quality control' => ['craftsmanship' => 20],

        // ── Community ────────────────────────────────────────────────
        'komunitas'       => ['community' => 25],
        'community'       => ['community' => 25],
        'kebersamaan'     => ['community' => 25],
        'bersama'         => ['community' => 18],
        'bareng'          => ['community' => 15],
        'ramah'           => ['community' => 20, 'personal_connection' => 10],
        'hangat'          => ['community' => 18, 'personal_connection' => 12],
        'dekat'           => ['community' => 15, 'personal_connection' => 15],
        'kolaborasi'      => ['community' => 15, 'innovation' => 10],
        'rekomendasikan'  => ['community' => 18],
        'rekomendasi teman' => ['community' => 22],
        'word of mouth'   => ['community' => 20],
        'referral'        => ['community' => 18],
        'teman'           => ['community' => 12, 'personal_connection' => 10],
        'keluarga'        => ['community' => 18, 'personal_connection' => 12],
        'saling'          => ['community' => 15],
        'berbagi'         => ['community' => 15],
        'gathering'       => ['community' => 18],
        'event komunitas' => ['community' => 22],
        'loyal'           => ['community' => 15, 'authority' => 8],
        'member'          => ['community' => 15],
        'pelanggan setia' => ['community' => 18, 'authority' => 5],

        // ── Innovation ───────────────────────────────────────────────
        'kreatif'         => ['innovation' => 20],
        'inovatif'        => ['innovation' => 25],
        'inovasi'         => ['innovation' => 25],
        'modern'          => ['innovation' => 15, 'lifestyle' => 10],
        'terbaru'         => ['innovation' => 15],
        'canggih'         => ['innovation' => 20],
        'teknologi'       => ['innovation' => 18],
        'digital'         => ['innovation' => 15],
        'visioner'        => ['innovation' => 22],
        'unik'            => ['innovation' => 12, 'personal_connection' => 8],
        'beda'            => ['innovation' => 12],
        'berbeda'         => ['innovation' => 12],
        'belum ada'       => ['innovation' => 18],
        'pertama kali'    => ['innovation' => 15],
        'satu-satunya'    => ['innovation' => 18],
        'original'        => ['innovation' => 15, 'craftsmanship' => 5],
        'cutting edge'    => ['innovation' => 22],
        'disrupsi'        => ['innovation' => 20],
        'startup'         => ['innovation' => 15],
        'custom'          => ['innovation' => 12, 'personal_connection' => 12],

        // ── Authority ────────────────────────────────────────────────
        'ahli'            => ['authority' => 25],
        'pakar'           => ['authority' => 25],
        'profesional'     => ['authority' => 20],
        'berpengalaman'   => ['authority' => 20],
        'pengalaman'      => ['authority' => 15],
        'expert'          => ['authority' => 25],
        'terpercaya'      => ['authority' => 20, 'community' => 8],
        'kredibel'        => ['authority' => 20],
        'bersertifikat'   => ['authority' => 22, 'craftsmanship' => 8],
        'sertifikasi'     => ['authority' => 20],
        'certified'       => ['authority' => 20],
        'terlatih'        => ['authority' => 15],
        'kompeten'        => ['authority' => 18],
        'konsultan'       => ['authority' => 20],
        'trainer'         => ['authority' => 18],
        'narasumber'      => ['authority' => 20],
        'riset'           => ['authority' => 18, 'innovation' => 10],
        'penelitian'      => ['authority' => 15, 'innovation' => 8],
        'data'            => ['authority' => 12],
        'terbukti'        => ['authority' => 18, 'transformation' => 10],

        // ── Lifestyle ────────────────────────────────────────────────
        'gaya hidup'      => ['lifestyle' => 25],
        'lifestyle'       => ['lifestyle' => 25],
        'estetik'         => ['lifestyle' => 22, 'craftsmanship' => 5],
        'aesthetic'       => ['lifestyle' => 22, 'craftsmanship' => 5],
        'estetika'        => ['lifestyle' => 22],
        'stylish'         => ['lifestyle' => 20],
        'kekinian'        => ['lifestyle' => 20, 'innovation' => 8],
        'trendy'          => ['lifestyle' => 20, 'innovation' => 8],
        'tren'            => ['lifestyle' => 15, 'innovation' => 8],
        'fashion'         => ['lifestyle' => 20],
        'keren'           => ['lifestyle' => 15],
        'instagramable'   => ['lifestyle' => 18],
        'instagrammable'  => ['lifestyle' => 18],
        'aesthetic feed'  => ['lifestyle' => 20],
        'feed'            => ['lifestyle' => 12],
        'inspirasi'       => ['lifestyle' => 15, 'transformation' => 8],
        'aspirasional'    => ['lifestyle' => 20],
        'impian'          => ['lifestyle' => 15, 'transformation' => 10],
        'status'          => ['lifestyle' => 15],

        // ── Value Driven ─────────────────────────────────────────────
        'jujur'           => ['value_driven' => 25],
        'kejujuran'       => ['value_driven' => 25],
        'integritas'      => ['value_driven' => 25],
        'prinsip'         => ['value_driven' => 20],
        'idealisme'       => ['value_driven' => 20],
        'nilai'           => ['value_driven' => 15],
        'etika'           => ['value_driven' => 20],
        'transparan'      => ['value_driven' => 20, 'personal_connection' => 10],
        'transparansi'    => ['value_driven' => 20, 'personal_connection' => 8],
        'halal'           => ['value_driven' => 22, 'local_pride' => 10],
        'organik'         => ['value_driven' => 15, 'craftsmanship' => 10],
        'organic'         => ['value_driven' => 15, 'craftsmanship' => 10],
        'ramah lingkungan' => ['value_driven' => 22],
        'eco friendly'    => ['value_driven' => 22],
        'sustainable'     => ['value_driven' => 22],
        'berkelanjutan'   => ['value_driven' => 20],
        'amanah'          => ['value_driven' => 22, 'authority' => 5],
        'terjangkau'      => ['value_driven' => 15, 'efficiency' => 10],
        'murah'           => ['value_driven' => 12, 'efficiency' => 12],
        'hemat'           => ['value_driven' => 10, 'efficiency' => 15],
        'tidak profit'    => ['value_driven' => 18],
        'sosial'          => ['value_driven' => 12, 'community' => 12],

        // ── Efficiency ───────────────────────────────────────────────
        'cepat'           => ['efficiency' => 20],
        'kilat'           => ['efficiency' => 20],
        'efisien'         => ['efficiency' => 25],
        'efisiensi'       => ['efficiency' => 25],
        'praktis'         => ['efficiency' => 20],
        'mudah'           => ['efficiency' => 18],
        'simpel'          => ['efficiency' => 18],
        'simple'          => ['efficiency' => 18],
        'instant'         => ['efficiency' => 20],
        'express'         => ['efficiency' => 20],
        'same day'        => ['efficiency' => 22],
        'hari ini'        => ['efficiency' => 15],
        'real time'       => ['efficiency' => 15],
        'otomatis'        => ['efficiency' => 15, 'innovation' => 10],
        'langsung'        => ['efficiency' => 15],
        'tanpa ribet'     => ['efficiency' => 18],
        'no hassle'       => ['efficiency' => 18],
        'one stop'        => ['efficiency' => 15],
        'all in one'      => ['efficiency' => 15],
        'hemat waktu'     => ['efficiency' => 20],

        // ── Personal Connection ──────────────────────────────────────
        'personal'        => ['personal_connection' => 20],
        'pribadi'         => ['personal_connection' => 18],
        'cerita'          => ['personal_connection' => 18, 'transformation' => 5],
        'story'           => ['personal_connection' => 18],
        'behind the scene' => ['personal_connection' => 22],
        'bts'             => ['personal_connection' => 18],
        'keseharian'      => ['personal_connection' => 20],
        'sehari-hari'     => ['personal_connection' => 18],
        'perjalanan'      => ['personal_connection' => 15, 'transformation' => 10],
        'perjuangan'      => ['personal_connection' => 18, 'transformation' => 12],
        'terbuka'         => ['personal_connection' => 15, 'value_driven' => 10],
        'autentik'        => ['personal_connection' => 18, 'local_pride' => 5],
        'authentic'       => ['personal_connection' => 18],
        'diri sendiri'    => ['personal_connection' => 15],
        'tampil sendiri'  => ['personal_connection' => 18],
        'kamera sendiri'  => ['personal_connection' => 18],
        'solo founder'    => ['personal_connection' => 20],
        'owner sendiri'   => ['personal_connection' => 20],

        // ── Local Pride ──────────────────────────────────────────────
        'lokal'           => ['local_pride' => 25],
        'local'           => ['local_pride' => 20],
        'indonesia'       => ['local_pride' => 20],
        'nusantara'       => ['local_pride' => 25],
        'daerah'          => ['local_pride' => 20],
        'budaya'          => ['local_pride' => 25],
        'tradisional'     => ['local_pride' => 20, 'craftsmanship' => 10],
        'warisan'         => ['local_pride' => 22, 'craftsmanship' => 8],
        'heritage'        => ['local_pride' => 20, 'craftsmanship' => 10],
        'kearifan lokal'  => ['local_pride' => 25],
        'batik'           => ['local_pride' => 22, 'craftsmanship' => 15],
        'tenun'           => ['local_pride' => 22, 'craftsmanship' => 15],
        'kerajinan'       => ['local_pride' => 18, 'craftsmanship' => 15],
        'dukung lokal'    => ['local_pride' => 25],
        'bangga lokal'    => ['local_pride' => 25],
        'produk lokal'    => ['local_pride' => 22],
        'made in indonesia' => ['local_pride' => 25],
        'buatan indonesia' => ['local_pride' => 25],
        'ukm'             => ['local_pride' => 15],
        'umkm'            => ['local_pride' => 15],

        // ── Transformation ───────────────────────────────────────────
        'transformasi'    => ['transformation' => 25],
        'berubah'         => ['transformation' => 20],
        'perubahan'       => ['transformation' => 20],
        'hasil nyata'     => ['transformation' => 22],
        'terbukti'        => ['transformation' => 18, 'authority' => 8],
        'sebelum sesudah' => ['transformation' => 25],
        'before after'    => ['transformation' => 25],
        'sebelum'         => ['transformation' => 10],
        'sesudah'         => ['transformation' => 10],
        'upgrade'         => ['transformation' => 18, 'innovation' => 10],
        'solusi'          => ['transformation' => 15, 'authority' => 8],
        'masalah teratasi' => ['transformation' => 20],
        'sembuh'          => ['transformation' => 20],
        'berhasil'        => ['transformation' => 18, 'authority' => 5],
        'sukses'          => ['transformation' => 15, 'authority' => 10],
        'progress'        => ['transformation' => 15],
        'naik'            => ['transformation' => 12],
        'meningkat'       => ['transformation' => 15],
        'lebih baik'      => ['transformation' => 18],
        'level up'        => ['transformation' => 18, 'innovation' => 8],
    ];

    /**
     * Communication strategy templates — one per DNA type.
     */
    const STRATEGIES = [
        'craftsmanship' => [
            'content_mix'    => [
                ['label' => 'Edukasi Kualitas Produk', 'pct' => 40],
                ['label' => 'Behind The Scenes Proses', 'pct' => 30],
                ['label' => 'Cerita & Nilai Owner',    'pct' => 20],
                ['label' => 'Promosi & CTA',            'pct' => 10],
            ],
            'content_pillars' => ['Detail & Proses Produksi', 'Proof of Quality', 'Material & Standar'],
            'posting_tone'    => 'Bangga, presisi, edukatif — tunjukkan "kenapa lebih baik" dengan bukti nyata',
            'hook_style'      => 'Fakta mengejutkan tentang proses atau bahan yang jarang orang tahu',
        ],
        'community' => [
            'content_mix'    => [
                ['label' => 'User Generated Content',  'pct' => 40],
                ['label' => 'Konten Komunitas & Event', 'pct' => 30],
                ['label' => 'Testimoni & Social Proof', 'pct' => 20],
                ['label' => 'Promosi & CTA',             'pct' => 10],
            ],
            'content_pillars' => ['Cerita Pelanggan', 'Event & Komunitas', 'Behind The Community'],
            'posting_tone'    => 'Hangat, inklusif, "kita bersama" — audiens adalah bagian dari cerita',
            'hook_style'      => 'Ajakan bergabung atau cerita nyata dari anggota komunitas',
        ],
        'innovation' => [
            'content_mix'    => [
                ['label' => 'Edukasi & Tren Industri',  'pct' => 35],
                ['label' => 'Showcase Inovasi Produk',   'pct' => 30],
                ['label' => 'POV & Thought Leadership',  'pct' => 25],
                ['label' => 'Promosi & CTA',              'pct' => 10],
            ],
            'content_pillars' => ['Tren & Masa Depan', 'Fitur & Cara Baru', 'Pikiran Berbeda'],
            'posting_tone'    => 'Futuristik, percaya diri, visioner — selalu satu langkah lebih maju',
            'hook_style'      => '"Cara lama sudah ketinggalan, ini cara baru yang lebih efektif"',
        ],
        'authority' => [
            'content_mix'    => [
                ['label' => 'Konten Edukasi Mendalam',  'pct' => 45],
                ['label' => 'Case Study & Hasil Nyata', 'pct' => 25],
                ['label' => 'Tips & How-to Praktis',    'pct' => 20],
                ['label' => 'Promosi & CTA',             'pct' => 10],
            ],
            'content_pillars' => ['Keahlian & Pengetahuan', 'Bukti & Data', 'Edukasi Audiens'],
            'posting_tone'    => 'Berbobot, berbasis fakta, percaya diri — posisikan sebagai rujukan terpercaya',
            'hook_style'      => '"Kesalahan umum yang sering dilakukan" atau "Fakta yang jarang diketahui"',
        ],
        'lifestyle' => [
            'content_mix'    => [
                ['label' => 'Konten Aspirasional',      'pct' => 40],
                ['label' => 'Product Showcase Estetik', 'pct' => 30],
                ['label' => 'Kolaborasi & Feature',     'pct' => 20],
                ['label' => 'Promosi & CTA',             'pct' => 10],
            ],
            'content_pillars' => ['Estetika & Visual', 'Gaya Hidup Target', 'Inspirasi & Aspirasi'],
            'posting_tone'    => 'Estetik, aspiratif, FOMO-triggering — jadikan produk simbol identitas',
            'hook_style'      => 'Visual sangat menarik atau momen gaya hidup yang relatable',
        ],
        'value_driven' => [
            'content_mix'    => [
                ['label' => 'Edukasi & Transparansi',  'pct' => 35],
                ['label' => 'Cerita di Balik Produk',  'pct' => 30],
                ['label' => 'Dampak & Nilai Nyata',    'pct' => 25],
                ['label' => 'Promosi & CTA',            'pct' => 10],
            ],
            'content_pillars' => ['Transparansi & Kejujuran', 'Dampak Nyata', 'Nilai & Prinsip'],
            'posting_tone'    => 'Jujur, apa adanya, prinsip-driven — audiens yang tepat akan datang sendiri',
            'hook_style'      => '"Kami tidak akan pernah melakukan X karena kami percaya Y"',
        ],
        'efficiency' => [
            'content_mix'    => [
                ['label' => 'How-to & Tutorial Cepat', 'pct' => 40],
                ['label' => 'Perbandingan & Solusi',   'pct' => 30],
                ['label' => 'Testimoni Kepuasan',      'pct' => 20],
                ['label' => 'Promosi & CTA',            'pct' => 10],
            ],
            'content_pillars' => ['Kemudahan & Kecepatan', 'Solusi Praktis', 'Perbandingan Efektif'],
            'posting_tone'    => 'To the point, no-nonsense — setiap konten langsung menjawab kebutuhan',
            'hook_style'      => '"Cara X dalam Y langkah" atau "Stop buang waktu dengan cara lama"',
        ],
        'personal_connection' => [
            'content_mix'    => [
                ['label' => 'Cerita Personal Owner',    'pct' => 40],
                ['label' => 'Behind The Scenes Harian', 'pct' => 30],
                ['label' => 'Q&A & Interaksi Langsung', 'pct' => 20],
                ['label' => 'Promosi & CTA',             'pct' => 10],
            ],
            'content_pillars' => ['Keseharian Owner', 'Proses & Perjuangan', 'Interaksi Personal'],
            'posting_tone'    => 'Sangat personal, relatable, autentik — audiens harus merasa mengenal owner',
            'hook_style'      => 'Momen personal yang jujur atau "confession" yang sangat relatable',
        ],
        'local_pride' => [
            'content_mix'    => [
                ['label' => 'Cerita Lokal & Budaya',      'pct' => 35],
                ['label' => 'Produk dalam Konteks Lokal', 'pct' => 30],
                ['label' => 'Gerakan Bangga Lokal',        'pct' => 25],
                ['label' => 'Promosi & CTA',               'pct' => 10],
            ],
            'content_pillars' => ['Identitas & Budaya', 'Kualitas Lokal', 'Gerakan Bangga Lokal'],
            'posting_tone'    => 'Bangga, penuh makna — identitas lokal adalah kekuatan, bukan keterbatasan',
            'hook_style'      => '"Tidak semua orang tahu bahwa..." tentang kearifan atau produk lokal',
        ],
        'transformation' => [
            'content_mix'    => [
                ['label' => 'Before & After Stories',  'pct' => 40],
                ['label' => 'Proses & Journey',         'pct' => 30],
                ['label' => 'Testimoni Transformasi',   'pct' => 20],
                ['label' => 'Promosi & CTA',             'pct' => 10],
            ],
            'content_pillars' => ['Bukti Sebelum-Sesudah', 'Journey Pelanggan', 'Hasil yang Dicapai'],
            'posting_tone'    => 'Emosional, inspiratif, result-focused — tunjukkan transformasi nyata',
            'hook_style'      => '"Dulu seperti ini, sekarang setelah menggunakan [produk] menjadi..."',
        ],
    ];
}
